//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Lütfen müþteri adýný giriniz...")]
        [StringLength(50, ErrorMessage = "Müþteri adý 50 karakterden fazla olamaz...")]
        public string ad { get; set; }

        [Required(ErrorMessage = "Lütfen müþteri soyadýný giriniz...")]
        [StringLength(50, ErrorMessage = "Müþteri soyadý 50 karakterden fazla olamaz...")]
        public string soyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
