//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
